# Generated by Django 4.2.1 on 2023-05-08 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendrequest',
            name='status',
            field=models.CharField(choices=[('NOTHING', 'Nothing'), ('OUTGOING_REQUEST', 'Outgoing Request'), ('INCOMING_REQUEST', 'Incoming Request'), ('ALREADY_FRIENDS', 'Already Friends')], default='NOTHING', max_length=32),
        ),
    ]
