# Generated by Django 4.2.1 on 2023-05-09 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0003_friendship_delete_friend_remove_userprofile_friends_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Friendship',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
