# Generated by Django 4.2.1 on 2023-05-09 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0004_remove_userprofile_user_delete_friendship_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friendrequest',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='friendrequest',
            name='status',
        ),
        migrations.AddField(
            model_name='friendrequest',
            name='is_friends',
            field=models.BooleanField(default=False),
        ),
    ]
